name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 * * *' # automatic test while every day on 04:00 am at UTC+10
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: build
        run: |
          yarn
          yarn build