name: Gatsby Publish

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 * * *' # automatic test while every day on 04:00 am at UTC+10
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: gatsby publish
        uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.GATSBY_ACCESS_TOKEN }}
          deploy-branch: gh-pages